name: CI

on:
  # build on PR creation/updates
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: lts/hydrogen

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules1-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache generated files
        id: cache-generated-files
        uses: actions/cache@v3
        with:
          path: |
            src/state/data
            src/locales
          key: ${{ runner.os }}-generatedFiles-${{ hashFiles('**/yarn.lock') }}

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Load dependencies
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules1-

      - name: Load generated files
        id: cache-generated-files
        uses: actions/cache@v3
        with:
          path: |
            src/state/data
            src/locales
          key: ${{ runner.os }}-generatedFiles-${{ hashFiles('**/yarn.lock') }}

      - name: Unit Test
        run: yarn test    

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Load dependencies
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules1-

      - name: Load generated files
        id: cache-generated-files
        uses: actions/cache@v3
        with:
          path: |
            src/state/data
            src/locales
          key: ${{ runner.os }}-generatedFiles-${{ hashFiles('**/yarn.lock') }}

      - name: Run eslint
        run: yarn lint

  